name: pre-release

on:
  push:
    branches:
      - master

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
        # Install Docker
      - run: sudo apt-get update
      - run: sudo apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common
      - run: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      - run: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
      - run: sudo apt-get update
      - run: sudo apt-get install docker-ce docker-ce-cli containerd.io

        # Checkout and build
      - uses: actions/checkout@v2
      - run: DOCKER_BUILDKIT=1 docker build --output target .

        # Create pre-release
      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Latest Development Build
          files: |
            target/index.pdf
